---
- name: Initialize and Transfer Tower Files
  hosts: "{{ source_host }},{{ target_host }}"
  become: true
  gather_facts: false

  tasks:
    - name: Check connectivity to all hosts
      ansible.builtin.ping:
      register: ping_result

    - name: Fail if any host is unreachable
      ansible.builtin.fail:
        msg: "Host {{ inventory_hostname }} is unreachable."
      when: ping_result.ping is not defined

    - name: Set validator type fact for each host
      set_fact:
        source_validatr_type: "{{ hostvars[source_host].validator_type }}"
        target_validatr_type: "{{ hostvars[target_host].validator_type }}"

    - name: Debug Target Host Validator Type
      debug:
        msg: "Source validator type is {{ source_validatr_type }} and Target validator type is {{ target_validatr_type }}"
      when: source_validatr_type is defined and target_validatr_type is defined

    - name: Fail if validator type is not set
      fail:
        msg: "Validator type is not set. Please set it in the inventory."
      when:
        - source_validatr_type is not defined
        - target_validatr_type is not defined

- import_playbook: switch_off_identity.yml
  vars:
    off_host: "{{ source_host }}"
  when: source_validatr_type in ['jito']

- import_playbook: switch_off_firedancer_identity.yml
  vars:
    off_host: "{{ source_host }}"
  when: source_validatr_type in ['firedancer']

- import_playbook: switch_on_identity.yml
  vars:
    on_host: "{{ target_host }}"
  when: target_validatr_type in ['jito']

- import_playbook: switch_on_firedancer_identity.yml
  vars:
    on_host: "{{ target_host }}"
  when: target_validatr_type in ['firedancer']
