---
- name: Setup Solana Snapshot Finder
  hosts: all
  become: yes
  gather_facts: no
  vars_files:
    - ~/.slv/inventory.testnet.validators.yml
  tasks:
    # 1. Ensure pip3 and venv are installed
    - name: Install pip3 and venv if not present
      apt:
        name:
          - python3-pip
          - python3-venv
        state: present
      become: yes

    # 2. Check if Solana Snapshot Finder directory exists
    - name: Check if Solana Snapshot Finder directory exists
      stat:
        path: /home/solv/solana-snapshot-finder
      register: snapshot_finder_dir

    # 3. Gitリポジトリのクローン
    - name: Clone Solana Snapshot Finder repository
      git:
        repo: https://github.com/c29r3/solana-snapshot-finder.git
        dest: /home/solv/solana-snapshot-finder
        update: yes
      when: not snapshot_finder_dir.stat.exists

    # 4. Ensure correct ownership of solana-snapshot-finder directory
    - name: Ensure correct ownership of solana-snapshot-finder directory
      file:
        path: /home/solv/solana-snapshot-finder
        state: directory
        owner: solv
        group: solv
        recurse: yes

    # 5. Create virtual environment
    - name: Create virtual environment
      shell: |
        python3 -m venv venv
      args:
        chdir: /home/solv/solana-snapshot-finder
      become: false
      become_user: solv

    # 6. Activate virtual environment and install requirements
    - name: Install Python dependencies in virtual environment
      shell: |
        source ./venv/bin/activate && pip3 install -r requirements.txt
      args:
        chdir: /home/solv/solana-snapshot-finder
        executable: /bin/bash
      become: false
      become_user: solv

    - name: Run Snapshot Finder
      shell: |
        source ./venv/bin/activate && python3 snapshot-finder.py --snapshot_path /mnt/snapshot --version {{ hostvars[inventory_hostname].solana_version }} -r http://api.testnet.solana.com --min_download_speed 45
      args:
        chdir: /home/solv/solana-snapshot-finder
        executable: /bin/bash
      become: false
      become_user: solv
      async: 3600
      poll: 10
