---
- name: Clone and build Yellowstone GRPC with specific tag
  hosts: all
  vars_files:
    - ~/.slv/versions.yml
  become: true
  vars:
    working_dir: "/home/solv"
    repo_url: "https://github.com/rpcpool/yellowstone-grpc.git"
    geyser_config_template: "~/.slv/mainnet-rpc/geyser.json.j2"
    geyser_config_path: "/home/solv/geyser.json"
  tasks:
    - name: Ensure Cargo and Rust environment is loaded
      shell: |
        source ~/.profile
        rustup show
      args:
        executable: /bin/bash
      become_user: solv

    - name: Clone or update the Yellowstone GRPC repository with specific tag
      git:
        repo: "{{ repo_url }}"
        dest: "{{ working_dir }}/yellowstone-grpc"
        version: "{{ geyser_version }}"
        update: yes
      become_user: solv
      vars:
        geyser_version: "{{ mainnet_rpcs.geyser_version }}"

    - name: Copy the geyser.json configuration file
      template:
        src: "{{ geyser_config_template }}"
        dest: "{{ geyser_config_path }}"
        owner: solv
        group: solv
        mode: "0644"
      vars:
        x_token: "{{ mainnet_rpcs.x_token }}"

    - name: Build the project using Cargo
      shell: |
        source ~/.profile
        cargo build -r
      args:
        chdir: "{{ working_dir }}/yellowstone-grpc"
        executable: /bin/bash
      become_user: solv

    - name: Format and run config-check with Cargo
      shell: |
        source ~/.profile
        cargo fmt && cargo run --bin config-check -- --config '{{ geyser_config_path }}'
      args:
        chdir: "{{ working_dir }}/yellowstone-grpc"
        executable: /bin/bash
      become_user: solv
