---
- name: Deploy and configure Solana validator service
  hosts: all
  become: true
  tasks:
    - name: Ensure systemd service directory exists
      file:
        path: /etc/systemd/system
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Deploy solv.service systemd unit file
      template:
        src: ~/.slv/mainnet-rpc/solv.service.j2
        dest: /etc/systemd/system/solv.service
        owner: root
        group: root
        mode: "0644"

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable solv.service
      systemd:
        name: solv.service
        enabled: true

    - name: sudo chown solv:solv -R /mnt
      command: chown solv:solv -R /mnt
      become_user: root
