---
- name: Deploy start-validator script dynamically
  hosts: all
  become: true
  tasks:
    - name: Ensure /home/solv exists
      file:
        path: /home/solv
        state: directory
        owner: solv
        group: solv
        mode: '0755'

    - name: Generate start-validator.sh from template
      template:
        src: ~/.slv/mainnet-validator/start-mainnet-validator.sh.j2
        dest: /home/solv/start-validator.sh
        mode: '0755'
        owner: solv
        group: solv
      vars:
        vote_account: '{{ hostvars[inventory_hostname].vote_account }}'
        relayer_url: '{{ hostvars[inventory_hostname].relayer_url }}'
        block_engine_region: '{{ hostvars[inventory_hostname].block_engine_region }}'
        shredstream_address: '{{ hostvars[inventory_hostname].shredstream_address }}'
        port_rpc: '{{ hostvars[inventory_hostname].port_rpc }}'
        limit_ledger_size: '{{ hostvars[inventory_hostname].limit_ledger_size }}'

    # Make sure if solv user has permission for /mnt directory
    - name: Ensure /mnt directory belongs to solv
      file:
        path: /mnt
        state: directory
        owner: solv
        group: solv
        mode: '0755'
