---
- name: Install Agave3
  hosts: all
  become: true
  vars_files:
    - ~/.slv/versions.yml
  vars:
    agave_version: v{{ testnet_validators.version_agave }}
    agave_repo: https://github.com/anza-xyz/agave.git
    agave_install_dir: '/home/solv/agave'
    agave_bin_dir: '{{ agave_install_dir }}/bin'
  tasks:
    - name: Check if Rust is installed
      become: no
      shell: command -v rustc
      register: rust_check
      changed_when: false
      failed_when: false

    - name: Install Rust
      become: no
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
      when: rust_check.rc != 0
      args:
        executable: /bin/bash

    - name: Install build dependencies
      apt:
        name:
          - build-essential
          - pkg-config
          - libssl-dev
          - libudev-dev
          - libclang-dev
          - cmake
          - protobuf-compiler
          - git
          - curl
        state: present
        update_cache: yes

    - name: Git clone Agave3 repository
      become: no
      git:
        repo: '{{ agave_repo }}'
        dest: '{{ agave_install_dir }}'
        version: '{{ agave_version }}'
        force: yes

    - name: Build and install Agave
      become: no
      shell: |
        source $HOME/.cargo/env
        cd {{ agave_install_dir }}
        ./scripts/cargo-install-all.sh .
      args:
        executable: /bin/bash
      environment:
        PATH: "/home/solv/.cargo/bin:{{ ansible_env.PATH }}"
      register: build_result

    - name: Add Agave to PATH in .bashrc
      become: no
      lineinfile:
        path: '/home/solv/.bashrc'
        line: 'export PATH={{ agave_bin_dir }}:$PATH'
        state: present
        create: yes

    - name: Deploy Agave3 systemd service file
      template:
        src: ~/.slv/testnet-validator/solv-agave3.service.j2
        dest: /etc/systemd/system/solv.service
        owner: root
        group: root
        mode: '0644'
      register: service_updated

    - name: Verify Agave installation
      become: no
      shell: |
        {{ agave_bin_dir }}/agave-validator --version
      register: agave_version_check
      changed_when: false
      failed_when: false

    - name: Debug Agave version check
      debug:
        var: agave_version_check.stdout