---
- name: Install node_exporter on Ubuntu
  hosts: all
  become: yes
  vars:
    node_exporter_version: '1.9.0'
    node_exporter_file: 'node_exporter-{{ node_exporter_version }}.linux-amd64'
    node_exporter_url: 'https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_file }}.tar.gz'

  tasks:
    - name: Make sure if the dir /home/solv exists
      become_user: root
      shell: mkdir -p /home/solv

    - name: Download node_exporter
      become_user: root
      get_url:
        url: '{{ node_exporter_url }}'
        dest: '/home/solv/{{ node_exporter_file }}.tar.gz'
        mode: '0644'

    - name: Unarchive node_exporter
      become_user: root
      unarchive:
        src: '/home/solv/{{ node_exporter_file }}.tar.gz'
        dest: '/home/solv/'
        remote_src: yes

    - name: Copy node_exporter binary to /usr/local/bin
      copy:
        src: '/home/solv/{{ node_exporter_file }}/node_exporter'
        dest: '/usr/local/bin/node_exporter'
        owner: solv
        group: solv
        mode: '0755'
        remote_src: yes

    - name: Remove unnecessary files
      shell: rm -rf /home/solv/{{ node_exporter_file }}*

    - name: Create node_exporter systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'
        content: |
          [Unit]
          Description=Node Exporter
          After=network-online.target
          Wants=network-online.target

          [Service]
          User=solv
          Group=solv
          Type=simple
          ExecStart=/usr/local/bin/node_exporter
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
      notify:
        - daemon-reload
        - restart-node_exporter

    - name: Enable node_exporter service
      systemd:
        name: node_exporter
        enabled: yes

  handlers:
    - name: daemon-reload
      systemd:
        daemon_reload: yes

    - name: restart-node_exporter
      systemd:
        name: node_exporter
        state: restarted
        enabled: yes
