---
- name: Update Firedancer
  hosts: all
  become: yes
  become_user: solv
  vars_files:
    - ~/.slv/versions.yml
  tasks:
    - name: Clone Firedancer repository
      git:
        repo: https://github.com/firedancer-io/firedancer.git
        dest: /home/solv/firedancer
        update: yes
        force: yes
        version: v{{ mainnet_validators.version_firedancer }}

    - name: Initialize git submodules
      command: git submodule update --init --recursive
      args:
        chdir: /home/solv/firedancer
      retries: 3
      delay: 10

    - name: Run deps.sh script with yes (async/poll)
      shell: |
        yes y | ./deps.sh
      args:
        chdir: /home/solv/firedancer
      async: 300 # wait for 5 minutes
      poll: 15 # check every 15 seconds
      register: deps_result
      until: deps_result.rc == 0
      retries: 3
      delay: 10

    - name: Build Firedancer with make
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"
        . $HOME/.cargo/env
        make -j fdctl solana
      args:
        chdir: /home/solv/firedancer
        executable: /bin/bash
      register: build_result
      until: build_result.rc == 0
      retries: 3
      delay: 10

    - name: Create symbolic link for fdctl
      file:
        src: /home/solv/firedancer/build/native/gcc/bin/fdctl
        dest: /usr/local/bin/fdctl
        state: link
      become: yes
      become_user: root

    - name: Ensure /mnt directory has correct permissions
      shell: sudo chown -R solv:solv /mnt && sudo chmod -R 700 /mnt
      failed_when: false