---
- name: Run Command
  hosts: all
  become: true
  become_user: solv
  gather_facts: no
  tasks:
    - name: Stop Firedancer
      shell: . ~/.profile && sudo systemctl stop firedancer
      register: command_output

    - name: Display Command output
      debug:
        msg: '{{ inventory_hostname }} ({{ hostvars[inventory_hostname].name }}): Stop Firedancer: {{ command_output.stdout }}'
