---
- name: Wget Snapshot
  hosts: all
  become: true
  vars_files: ../cmn/config/config.yml
  become_user: solv

  tasks:
    - name: Wget Snapshot
      shell: |
        aria2c -x16 -s16 --force-sequential=true https://snapshots.avorio.network/mainnet-beta/snapshot.tar.bz2 https://snapshots.avorio.network/mainnet-beta/incremental-snapshot.tar.bz2
      args:
        chdir: /mnt/snapshot
        executable: /bin/bash
      async: 3600
      poll: 10
