# SLV Solana / Shredstream file descriptor limits
# Deployed by slv irq-tuning skill

* soft nofile 1000000
* hard nofile 1000000
solv soft nofile 1000000
solv hard nofile 1000000
root soft nofile 1000000
root hard nofile 1000000
