---
- name: Copy validator and vote key pairs
  hosts: all
  gather_facts: no
  vars_files:
    - ~/.slv/inventory.mainnet.validators.yml

  tasks:
    - name: Copy validator key file
      become: yes
      become_user: root
      copy:
        src: '~/.slv/keys/{{ hostvars[inventory_hostname].identity_account }}.json'
        dest: '/home/solv/mainnet-validator-keypair.json'
        owner: solv
        group: solv
        mode: '0600'
