---
- name: Stop Agave, Rm ledger, DL snapshot, and run Agave
  hosts: all
  become: yes
  tasks:
    - name: Stop solv.service
      ansible.builtin.systemd:
        name: solv.service
        state: stopped
      become: true
      become_user: root
      register: stop_service_result

    - name: Display stop service result
      ansible.builtin.debug:
        msg: '{{ inventory_hostname }}: Stopped solv.service.'

    - name: Remove all files in /mnt/ledger/ using rm -rf
      shell: sudo find /mnt/ledger/ -mindepth 1 -not -name 'contact-info.bin' -delete
      become: true
      become_user: root

    - name: Remove all files in /mnt/snapshot/ using rm -rf
      ansible.builtin.shell: rm -rf /mnt/snapshot/*
      become: true
      become_user: root

    - name: Install pip3 and venv if not present
      apt:
        name:
          - python3-pip
          - python3-venv
        state: present
      become: yes

    - name: Check if Solana Snapshot Finder directory exists
      stat:
        path: /home/solv/solana-snapshot-finder
      register: snapshot_finder_dir

    - name: Clone Solana Snapshot Finder repository
      git:
        repo: https://github.com/c29r3/solana-snapshot-finder.git
        dest: /home/solv/solana-snapshot-finder
        update: yes
      when: not snapshot_finder_dir.stat.exists

    - name: Ensure correct ownership of solana-snapshot-finder directory
      file:
        path: /home/solv/solana-snapshot-finder
        state: directory
        owner: solv
        group: solv
        recurse: yes

    - name: Create virtual environment
      shell: |
        python3 -m venv venv
      args:
        chdir: /home/solv/solana-snapshot-finder
      become: false
      become_user: solv

    - name: Install Python dependencies in virtual environment
      shell: |
        source ./venv/bin/activate && pip3 install -r requirements.txt
      args:
        chdir: /home/solv/solana-snapshot-finder
        executable: /bin/bash
      become: false
      become_user: solv

    - name: Run Snapshot Finder
      shell: |
        source ./venv/bin/activate && python3 snapshot-finder.py --snapshot_path /mnt/snapshot --version {{ hostvars[inventory_hostname].solana_version }} -r http://api.testnet.solana.com --min_download_speed 45
      args:
        chdir: /home/solv/solana-snapshot-finder
        executable: /bin/bash
      become: false
      become_user: solv
      async: 3600
      poll: 10

    - name: Start solv.service
      systemd:
        name: solv.service
        state: started
