---
- name: Change Identity and Restart firedancer.service
  hosts: all
  become: true
  become_user: solv

  tasks:
    - name: Stop firedancer.service
      ansible.builtin.systemd:
        name: firedancer.service
        state: stopped
      become: true
      become_user: root
      register: stop_service_result

    - name: Remove all files in /mnt/ledger/ using rm -rf
      shell: sudo find /mnt/ledger/ -mindepth 1 -not -name 'contact-info.bin' -delete
      become: true
      become_user: root

    - name: Remove all files in /mnt/snapshot/ using rm -rf
      ansible.builtin.shell: rm -rf /mnt/snapshot/*
      become: true
      become_user: root

    - name: Change Symbolic Link to Authoried Identity
      shell: ln -sf /home/solv/testnet-validator-keypair.json /home/solv/identity.json
      become: true
      become_user: solv

    - name: Start firedancer.service
      ansible.builtin.systemd:
        name: firedancer.service
        state: started
      become: true
      become_user: root
      register: start_service_result
