---
- name: Execute tasks as solv user
  hosts: all
  become: true
  become_user: solv
  tasks:
    - name: restart solv
      shell: . ~/.profile && agave-validator -l /mnt/ledger exit --max-delinquent-stake 10
      register: solana_version_output
