---
- name: Disable swap on all hosts
  hosts: all
  become: true
  vars:
  tasks:
    - name: Ensure swap is disabled
      block:
        - name: Check for active swap
          shell: swapon --show --noheadings --output NAME | awk '{print $1}'
          register: active_swap
          changed_when: false

        - name: Debug active swap devices
          debug:
            var: active_swap.stdout_lines

        - name: Disable active swap devices
          command: swapoff {{ item }}
          loop: "{{ active_swap.stdout_lines }}"
          when: active_swap.stdout_lines | length > 0

        - name: Remove swap entries from /etc/fstab
          replace:
            path: /etc/fstab
            regexp: ".*swap.*"
            replace: ""
          when: active_swap.stdout_lines | length > 0