---
- name: Configure needrestart for solv.service
  hosts: all
  become: true
  tasks:
    - name: Ensure needrestart configuration directory exists
      file:
        path: /etc/needrestart/conf.d
        state: directory
        mode: '0755'

    - name: Configure needrestart to exclude solv.service
      copy:
        content: '$nrconf{override_rc}{qr(^solv\.service$)} = 0;'
        dest: /etc/needrestart/conf.d/solv.conf
        owner: root
        group: root
        mode: '0644'

    - name: Configure needrestart to exclude firedancer.service
      copy:
        content: '$nrconf{override_rc}{qr(^firedancer\.service$)} = 0;'
        dest: /etc/needrestart/conf.d/firedancer.conf
        owner: root
        group: root
        mode: '0644'
