---
- name: Install Agave
  hosts: all
  become: true
  vars_files:
    - ~/.slv/versions.yml
  vars:
    solana_bin_dir: '/home/solv/.local/share/solana/install/active_release/bin'
  tasks:
    - name: Install Agave from the specified version
      shell: |
        tag=v{{ testnet_validators.version_agave }}
        curl -sSfL https://release.anza.xyz/${tag}/install | sh
      args:
        executable: /bin/bash
      environment:
        PATH: '{{ solana_bin_dir }}:{{ ansible_env.PATH }}'
        HOME: '/home/solv'

    - name: Verify Solana installation
      shell: '{{ solana_bin_dir }}/solana --version'
      register: solana_version_check
      failed_when: solana_version_check.rc != 0

    - name: Debug Solana version check
      debug:
        var: solana_version_check.stdout
