---
- name: Load validator type from inventory
  hosts: all
  gather_facts: no
  tasks:
    - name: Set validator type fact for each host
      set_fact:
        validator_type: "{{ validator_type | default('firedancer') }}"

    - name: Debug validator type. Stop if not set
      debug:
        msg: "Validator type is {{ validator_type }}"

    - name: Fail if validator type is not set
      fail:
        msg: "Validator type is not set. Please set it in the inventory."
      when: validator_type is not defined

- import_playbook: ../cmn/fix_permissions.yml
  when: validator_type in ['agave', 'firedancer']

- import_playbook: copy_keys.yml
  when: validator_type in ['firedancer']

- import_playbook: add_solv.yml
  when: validator_type in ['agave', 'firedancer']

- import_playbook: ../cmn/install_package.yml
  when: validator_type in ['agave', 'firedancer']

- import_playbook: ../cmn/setup_node_exporter.yml

- import_playbook: ../cmn/setup_ufw.yml
  when: validator_type in ['firedancer']

- import_playbook: setup_agave_ufw.yml
  when: validator_type in ['agave']

- import_playbook: ../cmn/install_rust.yml
  when: validator_type in ['agave', 'firedancer']

- import_playbook: install_agave.yml
  when: validator_type == 'agave'

- import_playbook: install_jito.yml
  when: validator_type == 'firedancer'

- import_playbook: setup_firedancer.yml
  when: validator_type == 'firedancer'

- import_playbook: ../cmn/disable_swap.yml
  when: validator_type in ['agave', 'firedancer']

- import_playbook: ../cmn/mount_disks.yml
  when: validator_type in ['agave', 'firedancer']

- import_playbook: ../cmn/optimize_system.yml
  when: validator_type in ['agave', 'firedancer']

- import_playbook: setup_solv_service_init.yml
  when: validator_type in ['agave']

- import_playbook: ../cmn/setup_norestart.yml
  when: validator_type in ['agave', 'firedancer']

- import_playbook: ../cmn/setup_logrotate.yml
  when: validator_type in ['agave', 'firedancer']

- import_playbook: ../cmn/setup_unstaked_identity.yml
  when: validator_type in ['agave', 'firedancer']

- import_playbook: deploy-start-validator-sh.yml
  when: validator_type == 'agave'

- import_playbook: wget_snapshot.yml
  when: validator_type in ['agave', 'firedancer']

- import_playbook: start_solv.yml
  when: validator_type == 'agave'

- import_playbook: start_firedancer.yml
  when: validator_type == 'firedancer'
