---
- name: Check if /dev/{{ disk_name }} is already formatted
  command: blkid /dev/{{ disk_name }}
  register: blkid_result
  failed_when: false
  changed_when: false

- name: Format /dev/{{ disk_name }} to ext4 if not already formatted
  filesystem:
    fstype: ext4
    dev: "/dev/{{ disk_name }}"
  when: blkid_result.stdout == ""

- name: Mount /dev/{{ disk_name }} to {{ mount_path }}
  mount:
    path: "{{ mount_path }}"
    src: "/dev/{{ disk_name }}"
    fstype: ext4
    state: mounted
    opts: defaults,noatime
