---
- name: Setup UFW
  hosts: all
  become: yes
  vars_files:
    - ~/.slv/versions.yml
  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Enable UFW and set default policies
      ufw:
        state: enabled
        direction: incoming
        policy: deny

    - name: Allow SSH from all IPs
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Allow ports 8000-8025 TCP
      ufw:
        rule: allow
        port: "8000:8025"
        proto: tcp

    - name: Allow ports 8000-8025 UDP
      ufw:
        rule: allow
        port: "8000:8025"
        proto: udp