---
- name: Create and link Solana identity files
  hosts: all
  become: true
  tasks:
    - name: Create unstaked-identity.json using solana-keygen
      shell: |
        sudo -u solv bash -c 'source ~/.profile && solana-keygen new --outfile /home/solv/unstaked-identity.json --no-passphrase'
      args:
        creates: /home/solv/unstaked-identity.json # Skip if file already exists

    - name: Ensure /home/solv/identity.json is a symlink to unstaked-identity.json
      file:
        src: /home/solv/unstaked-identity.json
        dest: /home/solv/identity.json
        state: link

    - name: Update ownership of identity.json symlink
      command: chown --no-dereference solv:solv /home/solv/identity.json
