---
- name: Setup UFW
  hosts: all
  become: yes
  vars_files:
    - ~/.slv/versions.yml
  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Enable UFW and set default policies
      ufw:
        state: enabled
        direction: incoming
        policy: deny

    - name: Allow SSH only from allowed_ssh_ips
      ufw:
        rule: allow
        port: 22
        proto: tcp
        src: "{{ item }}"
      loop: "{{ mainnet_rpcs.allowed_ssh_ips }}"
      when: mainnet_rpcs.allowed_ssh_ips is defined

    - name: Allow SSH from all IPs
      ufw:
        rule: allow
        port: 22
        proto: tcp
      when: mainnet_rpcs.allowed_ssh_ips is not defined

    - name: Allow ports 8000-8020 TCP
      ufw:
        rule: allow
        port: "8000:8020"
        proto: tcp

    - name: Allow ports 8000-8020 UDP
      ufw:
        rule: allow
        port: "8000:8020"
        proto: udp

    - name: Allow all ports (TCP & UDP) from Known IPs
      ufw:
        rule: allow
        proto: any
        from_ip: "{{ item }}"
      loop: "{{ mainnet_rpcs.allowed_ips }}"
      when: mainnet_rpcs.allowed_ips is defined
