---
- name: Deploy and configure Solana validator service
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Ensure systemd service directory exists
      file:
        path: /etc/systemd/system
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Deploy solv.service systemd unit file
      template:
        src: ~/.slv/mainnet-validator/solv.service.j2
        dest: /etc/systemd/system/solv.service
        owner: root
        group: root
        mode: '0644'

    - name: Ensure /mnt directory has correct permissions
      shell: sudo chown -R solv:solv /mnt && sudo chmod -R 700 /mnt

    - name: Reload systemd daemon
      command: systemctl daemon-reload
