---
- name: Rm ledger and snapshot except contact-info.bin
  hosts: all
  become: yes
  tasks:
    - name: Remove all files in /mnt/ledger/ using rm -rf except contact-info.bin
      shell: sudo find /mnt/ledger/ -mindepth 1 -not -name 'contact-info.bin' -delete
      become: true
      become_user: root

    - name: Remove all files in /mnt/snapshot/ using rm -rf
      ansible.builtin.shell: rm -rf /mnt/snapshot/*
      become: true
      become_user: root
