---
- name: Load RPC type from inventory
  hosts: all
  gather_facts: no
  tasks:
    - name: Set RPC type fact for each host
      set_fact:
        rpc_type: "{{ rpc_type | default('Geyser gRPC') }}"
    
    - name: Debug RPC type. Stop if not set
      debug:
        msg: "RPC type is {{ rpc_type }}"

    - name: Fail if RPC type is not set
      fail:
        msg: "RPC type is not set. Please set it in the inventory."
      when: rpc_type is not defined


- import_playbook: ../cmn/fix_permissions.yml
- import_playbook: copy_restart_sh.yml
- import_playbook: copy_keys.yml
- import_playbook: add_solv.yml
- import_playbook: ../cmn/update_ubuntu.yml
- import_playbook: ../cmn/install_package.yml
- import_playbook: ../cmn/setup_node_exporter.yml
- import_playbook: install_rust.yml
- import_playbook: install_jito.yml
- import_playbook: setup_ufw.yml
- import_playbook: ../cmn/disable_swap.yml
- import_playbook: ../cmn/mount_disks.yml
- import_playbook: ../cmn/optimize_system.yml
- import_playbook: ../cmn/setup_norestart.yml
- import_playbook: configure_hugetlbfs.yml
- import_playbook: setup_logrotate.yml
- import_playbook: ../cmn/setup_unstaked_identity.yml
- import_playbook: update_startup_config.yml
- import_playbook: setup-solv-service.yml

- import_playbook: geyser_build.yml
  when: rpc_type == 'Geyser gRPC'

- import_playbook: wget_snapshot.yml
- import_playbook: start-solv-service.yml
