- name: Allow all inventory IPs in UFW
  hosts: all
  gather_facts: no
  become: true

  tasks:
    - name: Collect all inventory IPs
      set_fact:
        all_ips: "{{ groups['all'] | map('extract', hostvars, 'ansible_host') | list }}"

    - name: Show collected IPs (確認用)
      debug:
        msg: '{{ all_ips }}'

    - name: Allow all ports (TCP & UDP) from Known IPs
      ufw:
        rule: allow
        proto: any
        from_ip: '{{ item }}'
      loop: '{{ all_ips }}'
