---
- name: Configure log rotation for Solana validator
  hosts: all
  become: true
  tasks:
    - name: Ensure logrotate configuration directory exists
      file:
        path: /etc/logrotate.d
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Create logrotate configuration for Solana validator
      copy:
        dest: /etc/logrotate.d/solana
        content: |
          /home/solv/solana-validator.log {
            su solv solv
            daily
            rotate 1
            size 4G
            missingok
            compress
            postrotate
              systemctl kill -s USR1 solv.service
            endscript
          }
        owner: root
        group: root
        mode: '0644'

    - name: Test logrotate configuration
      command: logrotate --debug /etc/logrotate.conf
      register: logrotate_debug
      failed_when: >
        logrotate_debug.rc != 0 or
        ('error:' in logrotate_debug.stderr.lower())
      changed_when: false
      ignore_errors: true

    - name: Debug logrotate test output
      debug:
        var: logrotate_debug.stdout

    - name: Force logrotate to apply the new configuration
      command: logrotate -f /etc/logrotate.conf
      register: logrotate_force
      changed_when: true
      ignore_errors: true
