---
- name: Stop DoubleZero daemon
  hosts: all
  become: yes
  gather_facts: false

  pre_tasks:
    - name: Check SSH reachability
      wait_for_connection:
        timeout: 10
      register: conn_check
      ignore_errors: true
      ignore_unreachable: true

    - meta: end_host
      when: conn_check.unreachable | default(false) or conn_check.failed | default(false)

  tasks:
    - name: Stop doublezerod
      ansible.builtin.systemd:
        name: doublezerod
        state: stopped
