CREATE TABLE IF NOT EXISTS `DevnetRpc` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `ansible_user` VARCHAR(64) NOT NULL,
  `ansible_host` VARCHAR(255) NOT NULL,
  `ansible_ssh_private_key_file` VARCHAR(512) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `identity_account` VARCHAR(64) NOT NULL,
  `region` VARCHAR(64) NOT NULL,
  `port_rpc` INT NOT NULL,
  `dynamic_port_range` VARCHAR(32) NOT NULL,
  `validator_type` VARCHAR(32) NOT NULL,
  `shred_receiver_address` VARCHAR(64) NOT NULL,
  `rpc_type` VARCHAR(64) NOT NULL,
  `limit_ledger_size` INT NOT NULL,
  `richat_version` VARCHAR(64) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `ux_devnet_rpc_name` (`name`),
  UNIQUE KEY `ux_devnet_rpc_identity` (`identity_account`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `MainnetRpc` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `ansible_user` VARCHAR(64) NOT NULL,
  `ansible_host` VARCHAR(255) NOT NULL,
  `ansible_ssh_private_key_file` VARCHAR(512) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `identity_account` VARCHAR(64) NOT NULL,
  `region` VARCHAR(64) NOT NULL,
  `port_rpc` INT NOT NULL,
  `dynamic_port_range` VARCHAR(32) NOT NULL,
  `validator_type` VARCHAR(32) NOT NULL,
  `shred_receiver_address` VARCHAR(64) NOT NULL,
  `rpc_type` VARCHAR(64) NOT NULL,
  `limit_ledger_size` INT NOT NULL,
  `richat_version` VARCHAR(64) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `ux_mainnet_rpc_name` (`name`),
  UNIQUE KEY `ux_mainnet_rpc_identity` (`identity_account`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `TestnetRpc` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `ansible_user` VARCHAR(64) NOT NULL,
  `ansible_host` VARCHAR(255) NOT NULL,
  `ansible_ssh_private_key_file` VARCHAR(512) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `identity_account` VARCHAR(64) NOT NULL,
  `region` VARCHAR(64) NOT NULL,
  `port_rpc` INT NOT NULL,
  `dynamic_port_range` VARCHAR(32) NOT NULL,
  `validator_type` VARCHAR(32) NOT NULL,
  `shred_receiver_address` VARCHAR(64) NOT NULL,
  `rpc_type` VARCHAR(64) NOT NULL,
  `limit_ledger_size` INT NOT NULL,
  `richat_version` VARCHAR(64) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `ux_testnet_rpc_name` (`name`),
  UNIQUE KEY `ux_testnet_rpc_identity` (`identity_account`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `MainnetValidator` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `ansible_user` VARCHAR(64) NOT NULL,
  `ansible_host` VARCHAR(255) NOT NULL,
  `ansible_ssh_private_key_file` VARCHAR(512) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `identity_account` VARCHAR(64) NOT NULL,
  `region` VARCHAR(64) NOT NULL,
  `port_rpc` INT NOT NULL,
  `dynamic_port_range` VARCHAR(32) NOT NULL,
  `validator_type` VARCHAR(32) NOT NULL,
  `shred_receiver_address` VARCHAR(64) NOT NULL,
  `vote_account` VARCHAR(64) NOT NULL,
  `authority_account` VARCHAR(64) NOT NULL,
  `commission_bps` INT NOT NULL,
  `relayer_url` VARCHAR(512) NOT NULL,
  `block_engine_url` VARCHAR(512) NOT NULL,
  `limit_ledger_size` INT NOT NULL,
  `staked_rpc_identity_account` VARCHAR(64) NOT NULL,
  `staked_rpc_amount` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `ux_mainnet_validator_name` (`name`),
  UNIQUE KEY `ux_mainnet_validator_identity` (`identity_account`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `TestnetValidator` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `ansible_user` VARCHAR(64) NOT NULL,
  `ansible_host` VARCHAR(255) NOT NULL,
  `ansible_ssh_private_key_file` VARCHAR(512) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `identity_account` VARCHAR(64) NOT NULL,
  `region` VARCHAR(64) NOT NULL,
  `port_rpc` INT NOT NULL,
  `dynamic_port_range` VARCHAR(32) NOT NULL,
  `validator_type` VARCHAR(32) NOT NULL,
  `shred_receiver_address` VARCHAR(64) NOT NULL,
  `vote_account` VARCHAR(64) NOT NULL,
  `authority_account` VARCHAR(64) NOT NULL,
  `commission_bps` INT NOT NULL,
  `relayer_url` VARCHAR(512) NOT NULL,
  `block_engine_url` VARCHAR(512) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `ux_testnet_validator_name` (`name`),
  UNIQUE KEY `ux_testnet_validator_identity` (`identity_account`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `Version` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `inventory_type` VARCHAR(32) NOT NULL,
  `version_agave` VARCHAR(64) NOT NULL,
  `version_firedancer` VARCHAR(64) NOT NULL,
  `version_jito` VARCHAR(64) NOT NULL,
  `version_jito_bam` VARCHAR(64),
  `geyser_version` VARCHAR(64),
  `richat_version` VARCHAR(64),
  `allowed_ssh_ips` JSON NOT NULL,
  `allowed_ips` JSON NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `ux_version_inventory_type` (`inventory_type`)
);
