- name: Setup Firedancer
  hosts: all
  become: yes
  tasks:
    - name: Check Ubuntu version
      debug:
        msg: 'Ubuntu version: {{ ansible_distribution_version }}'

    - name: Create ubuntu.sources file if Ubuntu version is 24.0 or later and less than 25.0
      copy:
        content: |
          Types: deb
          URIs: http://nl.archive.ubuntu.com/ubuntu/
          Suites: noble noble-updates noble-backports
          Components: main restricted universe multiverse
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

          Types: deb
          URIs: http://security.ubuntu.com/ubuntu/
          Suites: noble-security
          Components: main restricted universe multiverse
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
        dest: /etc/apt/sources.list.d/ubuntu.sources
        owner: root
        group: root
        mode: '0644'
      when: >
        (ansible_distribution_version is version('24.0', '>=')) and
        (ansible_distribution_version is version('25.0', '<'))
      ignore_errors: true

    - name: Remove /etc/apt/sources.list
      file:
        path: /etc/apt/sources.list
        state: absent
      when: >
        (ansible_distribution_version is version('24.0', '>=')) and
        (ansible_distribution_version is version('25.0', '<'))
      ignore_errors: true

    - name: Add explanation to /etc/apt/sources.list
      copy:
        content: "# Ubuntu sources have moved to /etc/apt/sources.list.d/ubuntu.sources\n"
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: '0644'
      when: >
        (ansible_distribution_version is version('24.0', '>=')) and
        (ansible_distribution_version is version('25.0', '<'))
      ignore_errors: true

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist
