export const AI_API_URL = 'https://ai.validators.solutions'
export const SLV_STORAGE_URL = 'https://storage.slv.dev'
export const METAL_API_URL = 'https://user-api.erpc.global/v3'
export const DISCORD_LINK = 'https://discord.gg/C7ZQSrCkYR'
export const USER_API_ORIGIN = 'https://user-api.erpc.global'
export const ERPC_DASHBOARD_URL = 'https://dashboard.erpc.global'
